# Generated by Django 4.2.5 on 2024-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
