# Generated by Django 4.2.5 on 2024-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_viewer', '0003_opportunity_created_time_opportunity_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
