# Generated by Django 4.2.5 on 2024-04-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_viewer', '0006_opportunity_latitude_opportunity_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp_viewer.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp_viewer.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp_viewer.userprofile')),
            ],
        ),
    ]
